
import ReduxProvider from "@/redux/store";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from 'react-hot-toast';
import DialogContent from "@/components/dialog/DialogContents";

export const metadata: Metadata = {
  title: "investor",
  description: "Generated by developerseyed@gmail.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ReduxProvider>
          {children}
          <DialogContent />
        </ReduxProvider>
        <Toaster />

      </body>
    </html>
  );
}
